checks:
    php: true
filter:
    paths: 
        - src/*
before_commands:
    - 'composer install --dev --prefer-source'
build:
    environment:
        php:
            version: 5.5
tools:
    php_code_sniffer: true
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_pdepend:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_hhvm: false
    php_mess_detector: true
    php_analyzer: true